Metrics/LineLength:
  Max: 99

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/**/*'
    - 'Gemfile'

Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/ExpandPathArguments:
  Enabled: false
Metrics/BlockLength:
  Exclude:
   - 'test/**/*.rb'